name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route:
  equatable:
  flutter_secure_storage:
  fluttertoast:
  flutter_animate:
  provider:
  get_it:
  go_router:
  dartz:
  hive_flutter:
  hive:
  freezed:
  freezed_annotation:
  json_serializable:
  path_provider:
  uuid:
  flutter_bloc:
  dio:
  # auto_route: ^7.8.0
  # equatable: ^2.0.0
  # flutter_animate: ^4.5.0
  # provider: ^6.1.1
  # get_it: ^7.6.7
  # go_router: ^13.1.0
  # dartz: ^0.10.1
  # hive_flutter: ^1.1.0
  # hive: ^2.2.3
  # freezed: ^2.4.6
  # freezed_annotation: ^2.4.1
  # json_serializable: ^6.7.1
  # path_provider: ^2.1.2
  # uuid: ^4.3.3
  # flutter_bloc: ^8.1.4
  # dio: ^5.4.3+1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  hive_generator: 
  auto_route_generator: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/